### ISSUE TITLE
Support for Spotify Playlist

### ISSUE THREAD

**Issue by Eric-sson** [aiguestdj/plex-extension#2]
Would it be possible to add support for Spotify Playlist?
I tried by either entering the url but receiving this message I'm sorry, but I can't access or provide content from specific URLs, including Spotify playlists. Or by giving the description e.g. Spotify Playlist Rock Classics doesn't give the result.

Would be great if it would be able to lookup the playlist by url or description.

**Comment by jjdenhertog** [comment]
Great idea, the website actually already has a Spotify connection. So it should be fairly easy to include an "import playlist" page in the extension. Will add it soon.

**Comment by jjdenhertog** [comment]
@Eric-sson The feature has been added. When you update your installment to the latest version you will find an "import playlist" option in the main menu. Here you can add spotify playlists.

**Comment by Eric-sson** [comment]
Thanks for adding this. I have tried a few playlists and it's working. 
However I noticed that there is a limitation of 100 tracks. Playlists with over 100 tracks will just stop and only show the first 100 tracks. I believe that this is a limitation of the Spotify API. I am not a developer myself but maybe something can be implemented to load the playlist from Spotify in batches, first 100 tracks and then the next 100 tracks till there are no new tracks anymore?

**Comment by jjdenhertog** [comment]
@Eric-sson Can you share the playlist link we me? I haven't tried with playlists of that size!

**Comment by Eric-sson** [comment]
This one has 200 songs: https://open.spotify.com/playlist/37i9dQZF1DWXRqgorJj26U
It will stop at track 100 which Metallica - Seek & Destroy

And this one might be really challenging as it has 1,996 songs: https://open.spotify.com/playlist/37i9dQZF1DWTmvXBN4DgpA
It will stop at track 100 which is U2 - One

**Comment by jjdenhertog** [comment]
@Eric-sson The code has been updated to support infinite amount of tracks. Keep in mind though that the more tracks - the worse the performance is. For the Top 2000: To get the tracks from Spotify takes about 40 seconds. Than to match it with your Plex takes about 120 seconds.

And then to create the playlist in Plex takes minutes 🤯  I just did a test run and it matched almost all tracks which then resulted in a Plex playlist of 1949 tracks. 

<img width="515" alt="Screenshot 2024-04-11 at 16 24 23" src="https://github.com/aiguestdj/plex-extension/assets/880721/a0458770-b23d-487e-8e15-6b855fb68819">

**Comment by Eric-sson** [comment]
Wow this is great! I tested the Rock Classics with 200 songs and it is indeed working :)
Thanks a lot! Let me know how I can buy you a coffee or beer ;)

**Comment by jjdenhertog** [comment]
Hahaha awesome to hear ❤️  You can always [buy me a coffee](https://www.buymeacoffee.com/jjdenhertog). You would be the first 😂

**Comment by Eric-sson** [comment]
I tried this morning to import the Top 2000 playlist but I receive the below error.

_@http://192.168.4.158:9010/_next/static/chunks/319-15fb403c6d4018d7.js:123:6212
5121/ez.xhr</</u.onerror@http://192.168.4.158:9010/_next/static/chunks/319-15fb403c6d4018d7.js:123:20439

Any idea what is causing this? Another playlist with 290 songs was working fine.

**Comment by jjdenhertog** [comment]
@Eric-sson Could you include a screenshot?

**Comment by Eric-sson** [comment]
![Schermafbeelding 2024-04-12 om 11 57 26](https://github.com/aiguestdj/plex-extension/assets/34913327/b032110c-c1f9-496a-b96f-9f6cf5a15c67)

**Comment by Eric-sson** [comment]
@jjdenhertog that's for the below Top 2000 playlist

https://open.spotify.com/playlist/37i9dQZF1DWTmvXBN4DgpA

**Comment by jjdenhertog** [comment]
@Eric-sson it might be a connection time-out because it takes such a long time to handle the request. I will check do an extra check and see if I can create a more meaningful error message 😂

**Comment by jjdenhertog** [comment]
@Eric-sson It turned out to be a limitation at the website. Where there is a maximum request time of 30 seconds. To cover this I have moved the loading of the Spotify data to the extension. In order to get this to work you need to setup a Spotify App and add the client_id / client_secret to the environment variables.

I have updated the readme:
https://github.com/aiguestdj/plex-extension?tab=readme-ov-file#spotify-import

**Comment by Eric-sson** [comment]
Thanks it's working now! 👍
