### ISSUE TITLE
Some songs not being matched

### ISSUE THREAD

**Issue by Eric-sson** [aiguestdj/plex-extension#3]
I noticed that quite some songs are not being matched while I have them in my plex library.
This is the playlist that I synced: https://open.spotify.com/playlist/37i9dQZF1DWSBi5svWQ9Nk

The below songs are in my library but are not being matched:

Cyril - Stumblin' In
Mr. Belt & Wezol - It's Not Right But It's Okay
Jaxomy - Pedro
Taylor Swift - Fortnight
Flemming - Alles op gevoel
Rondé - Undecided
Indila - Dernière danse (Techno Mix)
Disturbed - The Sound of Silence (CYRIL Remix)
Yssi SB - Festival
David Guetta - I Don't Wanna Wait
Claude - Écoutez-moi
Tino Martin - Voor Je ‘t Weet
Lost Frequencies - Head Down
Donnie - Hier Mag Alles
Maan - Paranoia
Ella Henderson - Alibi (feat. Rudimental)
Kris Kross Amsterdam - Queen Of My Castle
Galantis - Lighter
LIZOT - This Is The Life
SativaMusic - Seya
Zerb - Mwaki
Goldband - You & Me

Do you have any idea what is causing this? All songs are properly tagged with Musicbrainz Picard.

**Comment by jjdenhertog** [comment]
@Eric-sson I'm moving the spotify / plex connection to a new project. Could you try it with that extension? It has the latest code for matching songs:

https://github.com/jjdenhertog/spotify-to-plex

_It's currently a rough version, I will probably updated it in a month_
